version: '3.7'

services:
  mysql-docker:
    container_name: mysql-docker
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
  app:
    container_name: quartzscheduler
    image: jamesmedice/quartzscheduler:latest
    depends_on:
      - mysql-docker
    links:
      - mysql-docker:db
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
    ports:
      - "8686:8686"
    command: mvn clean spring-boot:run -Djasypt.encryptor.password=keyMaster